### ISSUE TITLE
Milestone: create an upstream PR

### ISSUE THREAD

**Issue by dqbd** [dqbd/tiktoken#5]
- [x] Add back the pyo3 bindings, so we can build both Python version and JS version at the same time
- [x] Allow loading of embeddings via an argument. This is needed to make the resulting WASM blob smaller, as it is currently inlined during build.
- [ ] Examine the possibility of reintroduction of multithreading (not sure, if that is even needed however due to the sheer perf. difference between other JS libraries)
- [x] Feature parity match - adding special tokens support etc.
- [x] Investigate better packaging support for browsers and other runtimes.
- [ ] Create a more lightweight WASM build
- [x] Add CI build steps for testing integrations with bundlers etc

**Comment by dqbd** [comment]
Resolved in https://github.com/openai/tiktoken/pull/50
